Gestion_Activos/Gestion_Activos/Controllers/Rol_PermissionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gestion_Activos.Models;
using Gestion_Activos.Models.Class;
using Newtonsoft.Json.Linq;
using System.Web.Script.Serialization;
using Gestion_Activos.Models.Commons;

namespace Gestion_Activos.Controllers
{
    [Autenticado]
    public class Rol_PermissionsController : Controller
    {
        BMS_DATA_DENTEntities connection = new BMS_DATA_DENTEntities();
        #region views
        [Permission(Permiso = Permissions_Enum.Visualizar_Rol)]
        public ActionResult Index()
        {
            return View();
        }

        [Permission(Permiso = Permissions_Enum.Visualizar_Rol)]
        public ActionResult List_Roles()
        {
            var model = (from p in connection.SGA_ROLES
                         where p.ID > 1
                         orderby p.ID
                         select new Rol
                         {
                             id         = p.ID,
                             name       = p.NOMBRE_ROL,
                             permanet   = p.PERMANENTE.Value
                         });
            return View(model.ToList());
        }

        public ActionResult List_Permissions()
        {
            var model = Get_Permission_By_Id();
            return View(model.ToList());
        }

        [Permission(Permiso = Permissions_Enum.Registrar_Rol)]
        public ActionResult Create_Rol()
        {
            var model = Get_Permission_By_Id();
            return View(model.ToList());
        }

        [Permission(Permiso = Permissions_Enum.Editar_Rol)]
        public ActionResult Edit_Rol(int id_Rol=1)
        {
            Rol rol_edit    = Get_Rol_By_Id(id_Rol);
            var permisions  = Get_Permission_By_Id(id_Rol);
            rol_edit.list_permissions = permisions;
            return View(rol_edit);
        }

        [HttpPost]
        public ActionResult Save_Created_Rol(string name_Rol, string[] permisos)
        {
            int id_inserted = Save_Rol(name_Rol);
            string result   = Insert_Rol_Permissions(id_inserted, permisos);
            return RedirectToAction("List_Roles");
        }
        #endregion

        #region ajax calls
        [HttpPost]
        public JsonResult Save_Edited_Rol(string id_rol, string name_rol, string[] permisos)
        {
            string value = "";
            int id_int   = Convert.ToInt32(id_rol);
            Rol old_rol  = Get_Rol_By_Id(id_int);
            if (Utilities.IsNumeric(id_rol) && !old_rol.permanet)
            {
                string successful = Update_Rol(old_rol, id_int, name_rol);
                if (successful == "0" )
                {
                   string successful_D = Delete_Rol_Permissions(id_int);
                   string successful_I = Insert_Rol_Permissions(id_int, permisos);
                    if (successful_D == "0" && successful_I == "0")
                    {
                        value = "Update realizado con éxito";
                    }
                    else
                    {
                        value = successful_I + " " + successful_D;
                    }
                }
            }
            else
            {
                value = "Error al actualizar";
            }
            return Json(value);
        }

        [Permission(Permiso = Permissions_Enum.Eliminar_Rol)]
        public JsonResult Delete_Rol_Id(string id_rol)
        {
            string value="";
            if (Utilities.IsNumeric(id_rol))
            {
                int id_int      = Convert.ToInt32(id_rol);
                int cantUserRol = Get_Count_Users_Rol(id_int);
                if (cantUserRol == 0)
                {
                    value = Delete_Rol(id_int);
                    value = Delete_Rol_Permissions(id_int);
                    value = (value == "0") ? "Eliminado con éxito." : value;
                }
                else
                {
                    value = "No se puede borrar! Existen usuarios con el rol seleciconado.";
                }
            }
            else
            {
                value = "El rol es inválido";
            }
            return Json(value);
        }

        public JsonResult Validate_Name_Rol(string name_rol)
        {
            bool exist = false;
            Rol rol = Get_Rol_By_Name(name_rol);
            exist   = (rol == null)? false : true;
            return Json(exist);
        }

        [HttpPost]
        public JsonResult Get_Rols()
        {   
            List<Rol> rol_list = Get_Rol_List();
            Dictionary<string, string> list = new Dictionary<string, string>();
            foreach (var rol in rol_list)
            {
                list.Add(Convert.ToString(rol.id), rol.name);
            }
            return Json(list);
        }
        #endregion
        

        #region querys
        private List<Rol> Get_Rol_List()
        {
            var model = (from p in connection.SGA_ROLES
                         where p.ID != 1
                         select new Rol
                         {
                             id         = p.ID,
                             name       = p.NOMBRE_ROL,
                             permanet   = p.PERMANENTE.Value
                         });
            return model.ToList();
        }

        private Rol Get_Rol_By_Id(int id_Rol=1)
        {
            var model = (from p in connection.SGA_ROLES
                         where p.ID == id_Rol
                         select new Rol
                         {
                             id         = p.ID,
                             name       = p.NOMBRE_ROL,
                             permanet   = p.PERMANENTE.Value
                         }).FirstOrDefault();
            return model;
        }

        private Rol Get_Rol_By_Name(string name = "")
        {
            try {
                    var model = (from p in connection.SGA_ROLES
                        where p.NOMBRE_ROL == name
                        select new Rol
                        {
                            id       = p.ID,
                            name     = p.NOMBRE_ROL,
                            permanet = p.PERMANENTE.Value
                        }).FirstOrDefault();
                return model;
            } catch (Exception) {
                return null;
            }
        }

        private int Get_Last_Id_Rol_Inserted()
        {
            var id = (from p in connection.SGA_ROLES
                         select p.ID
                         ).Max();
            return id;
        }

        private int Get_Count_Users_Rol(int id_rol = 0)
        {
            var count = (from p in connection.SGA_USUARIOS
                         where p.ID == id_rol
                         select p).Count();
            return count;
        }

        private List<Permission> Get_Permission_By_Id(int id_rol=1)
        {
            var list = (from permission in connection.SGA_PERMISOS
                        join rolU in connection.SGA_ROLES_PERMISOS
                        on new { x = permission.ID, y = id_rol } equals new { x = rolU.ID_PERMISO, y = rolU.ID_ROL }
                        into UnionValues
                        from rolU in UnionValues.DefaultIfEmpty()
                        select new Permission
                        {
                            ID          = permission.ID,
                            Category    = permission.CATEGORIA.Value,
                            Description = permission.NOMBRE,
                            Active = (rolU == null ? false : true)
                        });
            return list.ToList();
        }

        //inserts- creates
        private string Insert_Rol_Permissions(int id_rol, string[] permissions)
        {
            string value = "0";
            foreach (var permission in permissions)
            {
                if (Utilities.IsNumeric(permission))
                {
                    SGA_ROLES_PERMISOS n_permi = new SGA_ROLES_PERMISOS()
                    {
                        ID_PERMISO = Convert.ToInt32(permission),
                        ID_ROL     = id_rol
                    };
                    connection.SGA_ROLES_PERMISOS.Add(n_permi);
                }
                try
                {
                    connection.SaveChanges();
                }
                catch (Exception e)
                {
                    value = "Error " + e;
                }
            } 
            return value;
        }

        private int Save_Rol(string name)
        {
            int id = 0;
            if (name != "" && name != null)
            {
                SGA_ROLES rol = new SGA_ROLES()
                {
                    NOMBRE_ROL = name,
                    PERMANENTE = false
                };
                connection.SGA_ROLES.Add(rol);
                try
                {
                    connection.SaveChanges();
                    id = Get_Last_Id_Rol_Inserted();
                }
                catch (Exception)
                {
                    return 0;
                }
            }
            return id;
        }

        
        //updates
        private string Update_Rol(Rol old_rol, int id_rol, string name_rol)
        {
            string value = "0";
            if (old_rol.name != name_rol) {
                var query = (from rols in connection.SGA_ROLES
                             where rols.ID == id_rol &&
                                   rols.PERMANENTE != true
                             select rols);
                foreach (SGA_ROLES rol in query)
                {
                    rol.NOMBRE_ROL = name_rol;
                }
                try
                {
                    connection.SaveChanges();
                }
                catch (Exception e)
                {
                    value = "Error " +e;
                }

Gestion_Activos/Gestion_Activos/Views/Rol_Permissions/Create_Rol.cshtml
@model IEnumerable<Gestion_Activos.Models.Class.Permission>

@{
    ViewBag.Title = "Crear Rol";
    Layout = "~/Views/MasterPage/MasterPage.cshtml";
}
@Styles.Render("~/bundle/scripts/checkboxcss")
@using (Html.BeginForm("Save_Created_Rol", "Rol_Permissions", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "validate_Form(event)" })) 
{
    @Html.AntiForgeryToken()    
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <i class="fa fa-save"></i>
                    Crear rol
                </div>

                <div class="col-lg-12">
                    <div class="form-group col-lg-3 col-xs-12">
                        <label for="nombreRol">Nombre del Rol:</label>
                        <input type="text" class="form-control" id="name_Rol" name="name_Rol" required="required" />
                    </div>
                    <div class="form-group">
                        <div class="col-lg-2 col-lg-offset-10 col-xs-12 col-xs-offset-0">
                            <input type="submit" id="click_post" class="btn btn-block btn-success btn-lg" value="Crear" />
                        </div>
                    </div>
                </div>

                <div class="box-body">
                    <center><h4>Seleccione los permisos del nuevo rol.</h4></center>
                    @foreach (var categorie in Categories_List.permisions_categories)
                    {
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2 col-xs-12">
                           <h3>@categorie.Value:</h3>
                            @foreach (var item in Model)
                            {
                                if (item.Category == categorie.Key)
                                {
                                <div class="col-xs-3">
                                    <div class="form-group">
                                        <label>
                                            <input type="checkbox" class="flat-red" value="@item.ID" name="permisos">
                                            @item.Description
                                        </label>
                                    </div>
                                </div>
                                }
                            }
                        </div>
                        <hr class="col-lg-8 col-lg-offset-2 col-xs-12">
                    </div>
                    }
                </div>

                <div class="box-footer">
                    <div class="form-group">
                        <div class="pull-left col-xs-4 col-lg-1 ">
                            <button type="button" class="btn btn-block btn-info btn-sm" onclick="location.href='@Url.Action("List_Roles")'">
                                Regresar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>
}

@Scripts.Render("~/bundle/scripts/checkboxjs")
<script src="@Url.Content("~/Scripts/Views/Rol_Permissions/Create_Rol.js")" type="text/javascript"></script>

Gestion_Activos/Gestion_Activos/Views/Rol_Permissions/Edit_Rol.cshtml
@model Gestion_Activos.Models.Class.Rol

@{
    ViewBag.Title = "Editar Rol";
    Layout = "~/Views/MasterPage/MasterPage.cshtml";
}

<input type="text" id="id_Rol"   value="@Model.id"   hidden="hidden"/>
<input type="text" id="edit" value="@Model.permanet" hidden="hidden" />
<form  name="formEdit" id="formEdit" method="post"></form>

@Styles.Render("~/bundle/scripts/checkboxcss")
<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary"> 
            <div class="box-header with-border">
                <i class="fa fa-save"></i>
                Editar Rol
            </div> 
            <div class="col-lg-12">
                <div class="form-group col-lg-3 col-xs-12">
                    <label for="nombreRol">Nombre del Rol:</label>
                    <input type="text" class="form-control"  id="name_Rol" value="@Model.name" readonly="@Model.permanet">
                </div>
                <div class="form-group">
                    @if (!Model.permanet){
                    <div class="col-lg-2 col-lg-offset-10 col-xs-12 col-xs-offset-0">
                        <input type="submit" id="click_post" class="btn btn-block btn-success btn-lg" value="Actualizar" />
                    </div>
                    }
                </div>
            </div>
            <div class="box-body">  
            @foreach (var categorie in Categories_List.permisions_categories)
            {
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-xs-12">
                    <h3>@categorie.Value:</h3>
                    @foreach (var item in Model.list_permissions)
                    { 
                        if (item.Category == categorie.Key)
                        {
                        <div class="col-xs-3">
                            <div class="form-group">
                                <label>
                                    @if (@item.Active)
                                    {
                                        <input type="checkbox" class="flat-red" value="@item.ID" name ="" checked="checked">
                                    }
                                    else
                                    {
                                        <input type="checkbox" class="flat-red" value="@item.ID" >
                                    }
                                    @item.Description
                                </label>
                            </div>
                        </div>
                        }
                    }
                </div>
                <hr class="col-lg-8 col-lg-offset-2 col-xs-12">
            </div>
            }
            </div>
            <div class="box-footer">
                <div class="form-group">
                    <div class="pull-left col-xs-4 col-lg-1 ">
                        <button type="button" class="btn btn-block btn-info btn-sm" onclick="location.href='@Url.Action("List_Roles")'">
                            Regresar
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="modal_editar_rol" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h3 class="modal-title">
                    <i class="fa  fa-info"></i>
                    Actualizando...
                </h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <center><h3 id="mjs">Se estan guardadndo los cambios, un momento por favor.</h3></center>
                </div>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundle/scripts/checkboxjs")
<script src="@Url.Content("~/Scripts/Views/Rol_Permissions/Edit_Rol.js")" type="text/javascript"></script>

Gestion_Activos/Gestion_Activos/Views/Rol_Permissions/List_Permissions.cshtml
@model IEnumerable<Gestion_Activos.Models.Class.Permission>
@{
    ViewBag.Title = "List_Permissions";
    Layout = "~/Views/MasterPage/MasterPage.cshtml";
}
@Styles.Render("~/bundle/scripts/checkboxcss")
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"></h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                @foreach (var categorie in Categories_List.permisions_categories)
                {
                <div class="row">
                    <center><h3>@categorie.Value</h3></center>
                    <div class="col-lg-8 col-lg-offset-2 col-xs-12">
                        @foreach (var item in Model)
                        {
                            if (item.Category == categorie.Key)
                            {
                            <div class="col-xs-3">
                                <div class="form-group">
                                    <label>
                                        <input type="checkbox" class="flat-red" value="@item.ID" checked="@item.Active">
                                        @item.Description
                                    </label>
                                </div>
                            </div>
                            }
                        }
                    </div>
                    <hr class="col-lg-8 col-lg-offset-2 col-xs-12">
                </div>
                }
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundle/scripts/checkboxjs")
<script src="@Url.Content("~/Scripts/Views/Rol_Permissions/List_Permissions.js")" type="text/javascript"></script>

Gestion_Activos/Gestion_Activos/Views/Rol_Permissions/List_Roles.cshtml
@model IEnumerable<Gestion_Activos.Models.Class.Rol>

@{
    ViewBag.Title = "Roles";
    Layout = "~/Views/MasterPage/MasterPage.cshtml";
}
<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <i class="fa fa-pencil-square-o"></i>
                Roles y permisos
            </div>

            <div class="col-lg-12">
                <h3 class="box-title"></h3>
                @if (FrontUser.Have_Permission(Permissions_Enum.Registrar_Rol)) { 
                <div class="col-xs-3">
                    <button type="button" class="btn btn-block btn-success btn-lg" onclick="location.href='@Url.Action("Create_Rol")'">
                        Crear Nuevo Rol
                    </button>
                </div>
                }
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="table1" class="table table-bordered table-hover" style="width:50%; margin:0 auto;">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.permanet)
                            </th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        { 
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.permanet)
                            </td>
                            <td>
                                <div class="form-group col-xs-12">
                                    @if (FrontUser.Have_Permission(Permissions_Enum.Editar_Rol)) { 
                                    <div class="pull-left col-xs-6">
                                        <button type="button" class="btn btn-block btn-info btn-sm" name="item.id" onclick="location.href='@Url.Action("Edit_Rol", new { id_Rol = item.id })'">
                                            Ver / Editar
                                        </button>
                                    </div>
                                    }
                                     @if (FrontUser.Have_Permission(Permissions_Enum.Eliminar_Rol))
                                     {
                                        if (item.permanet != true)
                                        {
                                        <div class="pull-right col-xs-6">
                                            <button type="button" class="btn btn-block btn-danger btn-sm" value="@item.id"  data-toggle="modal" data-target="#modal_confirmar_eliminar"  onclick="delete_User(@item.id);">
                                                Eliminar
                                            </button>
                                        </div>
                                        }
                                    }
                                </div>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="inp_id_rol">

<div class="modal fade" id="modal_confirmar_eliminar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h3 class="modal-title">
                    <i class="fa  fa-info"></i>
                    Actualizar
                </h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <center><h3>¿Seguro que desea eliminar el rol?</h3></center>
                    <br>
                    <div class="col-xs-12">
                        <div class="col-xs-6">
                            <button type="button" class="btn btn-block btn-danger btn-lg" data-dismiss="modal"><i class="fa fa-close"></i>Cancelar</button>
                        </div>
                        <div class="col-xs-6">
                            <button type="button" class="btn btn-block btn-success btn-lg" id="btn_confirmacion_eliminar"><i class="fa  fa-check"></i>Aceptar </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundle/scripts/dataTables")
<script src="@Url.Content("~/Scripts/Views/Rol_Permissions/List_Roles.js")" type="text/javascript"></script>